version: '3.3'

services:
  db:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'market'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
